// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ralymp.DataAccessLayer;

namespace Ralymp.Migrations
{
    [DbContext(typeof(RalympDbContext))]
    partial class RalympDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ralymp.Models.DatabaseTypes.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level");

                    b.Property<int>("Place");

                    b.Property<int?>("StudentId");

                    b.Property<int?>("SubjectId");

                    b.Property<int?>("TeacherId");

                    b.Property<int?>("YearInfoId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("YearInfoId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("Ralymp.Models.DatabaseTypes.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("School");
                });

            modelBuilder.Entity("Ralymp.Models.DatabaseTypes.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<int>("GraduationYear");

                    b.Property<int?>("SchoolId");

                    b.Property<string>("SecondName");

                    b.Property<string>("ThirdName");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Ralymp.Models.DatabaseTypes.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("Ralymp.Models.DatabaseTypes.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<int?>("SchoolId");

                    b.Property<string>("SecondName");

                    b.Property<string>("ThirdName");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Ralymp.Models.DatabaseTypes.YearInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullTitle");

                    b.HasKey("Id");

                    b.ToTable("YearInfo");
                });

            modelBuilder.Entity("Ralymp.Models.DatabaseTypes.Participation", b =>
                {
                    b.HasOne("Ralymp.Models.DatabaseTypes.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.HasOne("Ralymp.Models.DatabaseTypes.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("Ralymp.Models.DatabaseTypes.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.HasOne("Ralymp.Models.DatabaseTypes.YearInfo", "YearInfo")
                        .WithMany()
                        .HasForeignKey("YearInfoId");
                });

            modelBuilder.Entity("Ralymp.Models.DatabaseTypes.Student", b =>
                {
                    b.HasOne("Ralymp.Models.DatabaseTypes.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId");
                });

            modelBuilder.Entity("Ralymp.Models.DatabaseTypes.Teacher", b =>
                {
                    b.HasOne("Ralymp.Models.DatabaseTypes.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId");
                });
#pragma warning restore 612, 618
        }
    }
}
